version: '3'
services:
  redis:
   image: redis:3.0-alpine
   ports:
   - "6379:6379"
   volumes:
   - ./redis.conf:/data/redis.conf
  mysql:
   image: 'mysql:latest'
   environment:
    MYSQL_DATABASE: rss
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3307:3306"
   restart: always
    
  app:
    restart: always
    build: ./demo
    working_dir: /app
    ports:
    - "8080:8080"
    volumes:
      - ./demo:/app
      - ~/.m2:/root/.m2
   
    depends_on:
      - redis
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker